v0=int(input("Digite la velocidad inicial: "))
a=int(input("Digite aceleración: "))
x=int(input("Digite el desplazamiento total del objeto: "))
vfinal=v0+2*(a*x)
print("La velocidad final es de: {}".format(vfinal))